### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by philcali** [lsuits/grade_notify#1]
The grade notifications block is ready for testing. Notable changes from 1.9:
- The select page is now a Moodleform
- removed jquery dependency (YUI now manips the DOM)
- gave users ability to auto-apply notifications on future enrolled courses
- db cleanup through events
- notifications materialize in the form of notification message (popup, email, whatever else configured); straight email is now a backup method
- better notification message

**Comment by rrusso** [comment]
Please merge in for wed.

**Comment by philcali** [comment]
Ok cool. Everything looked good?

**Comment by rrusso** [comment]
Seems fine here.

**Comment by rrusso** [comment]
Was a little weirded out until I realized I wasn't in any courses. 

I guess it pays to turn the brain on before testing.
